name: Build and Test

on : 
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Build
      run: dotnet build CheckoutChallenge.PaymentGateway.sln --configuration Release
      working-directory: ./src/CheckoutChallenge.PaymentGateway
    - name: Run Tests
      run: dotnet test CheckoutChallenge.PaymentGateway.sln
      working-directory: ./src/CheckoutChallenge.PaymentGateway

